name: calibration
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1
  flutter_tindercard: 0.2.0
  firebase_auth: 0.18.3
  firebase_core: 0.5.2
  google_sign_in: 4.5.5
  http: 0.12.2
  cached_network_image: 2.4.1
  flutter_launcher_icons: 0.7.2
  splashscreen: 1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/ic-launcher.png"
  adaptive_icon_background: "#ff4500"
  adaptive_icon_foreground: "assets/ic-launcher.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Ruda
      fonts:
        - asset: fonts/Ruda.ttf
    - family: Exo
      fonts:
        - asset: fonts/Exo.ttf

